def ProjectName = "PearUp"
def EmailRecipients = "siva.kondabathini@ggktech.com"
def checkOutInformation

properties([
  parameters([
    string(name: 'DEPLOY_ENV', defaultValue: 'TESTING', description: 'The target environment', )
    choice(choices: ['US-EAST-1', 'US-WEST-2'], description: 'What AWS region?', name: 'region')
   ])
])

node('BuildNode')
{
  stage('GitHub Pull') { 
      sh "echo ${params.DEPLOY_ENV}"
      // Get some code from GitHub repository
      checkOutInformation = git credentialsId: '444d8b75-cf7c-4c8d-a8dc-bbcc321fed03', url: 'https://github.com/sivasankarkondabathini/PearUp.git'
  }
}
 
