def ProjectName = "PearUp"
def EmailRecipients = "siva.kondabathini@ggktech.com"
def checkOutInformation

node('BuildNode')
{
  parameters {
    choice(
      name: 'Nodes',
      choices:"Linux\nMac",
      description: "Choose Node!")
  }
  stage('GitHub Pull') { 
      sh "echo ${params.Nodes}"
      // Get some code from GitHub repository
      checkOutInformation = git credentialsId: '444d8b75-cf7c-4c8d-a8dc-bbcc321fed03', url: 'https://github.com/sivasankarkondabathini/PearUp.git'
  }
}
 
